default: &default
  adapter: postgresql
  host: localhost
  username: post_user
  password: root
  pool: 5
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: image_development

production:
  <<: *default
  database: image_production
